# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca1f54fea49211aa24766820a764cfb5d8ef0cd6da13c8448d03738c5b8eb63f3fb73f6796c1ca75dd068315265b0ef98af860d53ea1981c46896750fa519e6e

test:
  secret_key_base: 22300c08bfc33042b3f1666af24c5aa9df6b87d9d9d9f54a5029ee3685b1f99dad52cce1e4454a27ec30a43dadc6f82b8c40e5d93340c7a778fc9e17803303ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
